server:
  port: 8080
mysql:
  dsn: root:root@tcp(127.0.0.1:3306)/godb?charset=utf8&parseTime=true&loc=Local
  maxIdle: 10
  maxOpen: 100
redis:
  addr: 127.0.0.1:6379
  db: 0
  maxIdle: 10
  maxOpen: 100
